#!/bin/bash

[ "$UID" -eq 0 ] || exec sudo "$0" "$@"
binfolder=$(echo $PATH | cut -d ":" -f 1)
echo "Detectando carpeta de bin..."
sleep 0.3
echo "Carpeta detecatada: $binfolder"
echo "Moviendo..."
sleep 0.3
sudo cp gitdeploy $binfolder
echo "Listo, ya puedes usar gitdeploy"
